// The browser chrome: the fake browser window (address bar, nav buttons) that
// wraps every view. Content pages live inside a sandboxed iframe so the model's
// CSS can never touch the chrome. SERPs and the home page are our own markup.
import { getSettings, type Settings } from './settings';

const esc = (s: string) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

interface Boot { mode: 'home' | 'serp' | 'page' | 'settings'; cached: boolean; q?: string; url?: string; from?: string; ctx?: string; }

function shell(opts: { title: string; address: string; content: string; boot: Boot }): string {
  const bootJson = JSON.stringify(opts.boot).replace(/</g, '\\u003c');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(opts.title)}</title>
<link rel="stylesheet" href="/public/chrome.css">
</head>
<body>
<header id="chrome">
  <div class="nav">
    <button class="navbtn" id="back" title="Back">‹</button>
    <button class="navbtn" id="fwd" title="Forward">›</button>
    <button class="navbtn" id="reload" title="Reload">⟳</button>
    <button class="navbtn" id="home" title="Home">⌂</button>
  </div>
  <form id="omnibox" autocomplete="off">
    <span class="lock">🔒</span>
    <input id="address" name="q" value="${esc(opts.address)}" placeholder="archive search, or type any 4chan URL…" spellcheck="false">
  </form>
  <a class="navbtn gear" href="/settings" title="Settings — model & endpoint">⚙</a>
  <div class="brand">🍀 virtual&#8209;4chan <span class="brand-model" title="every byte generated by this model">${esc(getSettings().model)}</span></div>
</header>
<main id="viewport">
${opts.content}
</main>
<script>window.__BOOT=${bootJson};</script>
<script src="/public/app.js"></script>
</body>
</html>`;
}

interface BoardLink { code: string; name: string; }
interface BoardCategory { cat: string; items: BoardLink[]; }

const BOARDS: BoardCategory[] = [
  { cat: 'Japanese Culture', items: [
    { code: 'a',  name: 'Anime & Manga' },
    { code: 'c',  name: 'Anime/Cute' },
    { code: 'jp', name: 'Otaku Culture' },
    { code: 'h',  name: 'Hentai' },
    { code: 'vt', name: 'Virtual YouTubers' },
  ]},
  { cat: 'Video Games', items: [
    { code: 'v',   name: 'Video Games' },
    { code: 'vg',  name: 'Video Game Generals' },
    { code: 'vp',  name: 'Pokémon' },
    { code: 'vrpg',name: 'Video Games / RPG' },
    { code: 'vmg', name: 'Video Games / Mobile' },
    { code: 'vst', name: 'Video Games / Strategy' },
  ]},
  { cat: 'Interests', items: [
    { code: 'g',   name: 'Technology' },
    { code: 'sci', name: 'Science & Math' },
    { code: 'his', name: 'History & Humanities' },
    { code: 'lit', name: 'Literature' },
    { code: 'mu',  name: 'Music' },
    { code: 'tv',  name: 'Television & Film' },
    { code: 'ck',  name: 'Food & Cooking' },
    { code: 'fit', name: 'Fitness' },
    { code: 'diy', name: 'Do It Yourself' },
    { code: 'biz', name: 'Business & Finance' },
  ]},
  { cat: 'Creative', items: [
    { code: 'ic',  name: 'Artwork/Critique' },
    { code: 'po',  name: 'Papercraft & Origami' },
    { code: 'p',   name: 'Photography' },
    { code: '3',   name: '3DCG' },
    { code: 'gd',  name: 'Graphic Design' },
  ]},
  { cat: 'Other', items: [
    { code: 'b',   name: 'Random' },
    { code: 'pol', name: 'Politically Incorrect' },
    { code: 'int', name: 'International' },
    { code: 'x',   name: 'Paranormal' },
    { code: 'trv', name: 'Travel' },
    { code: 'k',   name: 'Weapons' },
    { code: 'r9k', name: 'ROBOT9001' },
  ]},
];

const BOARD_HOST = 'boards.4chan.org';

export function renderHome(stats: { pages: number; serps: number }): string {
  const groups = BOARDS.map((g) => {
    const items = g.items
      .map((b) => {
        const url = `https://${BOARD_HOST}/${b.code}/`;
        const anchor = `/${b.code}/`;
        return `<a class="bd" href="/view?url=${encodeURIComponent(url)}&ctx=${encodeURIComponent(anchor)}" title="${esc(b.name)}"><span class="bd-code">${esc(anchor)}</span><span class="bd-name">${esc(b.name)}</span></a>`;
      })
      .join('');
    return `<section class="bgrp"><h3>${esc(g.cat)}</h3><div class="bgrp-items">${items}</div></section>`;
  }).join('');

  const content = `<style>
    .ch4{background:#ffffee;color:#000;font-family:Arial,Helvetica,sans-serif;padding:22px 30px;min-height:100%}
    .ch4 .brand4{font-family:"Times New Roman",Times,serif;font-size:42px;font-weight:bold;color:#af0a0f;letter-spacing:1px;margin:0;line-height:1}
    .ch4 .brand4 .cn{color:#117743}
    .ch4 .tag{color:#444;margin:6px 0 14px 0;font-size:13px}
    .ch4 .modelpill4{display:inline-block;background:#f0e0d6;border:1px solid #d9bfb7;color:#800;padding:3px 10px;font-size:12px;margin-bottom:18px;border-radius:2px}
    .ch4 .modelpill4 code{background:transparent;font-family:Menlo,monospace}
    .ch4 .homebox4{display:flex;align-items:center;background:#fff;border:1px solid #b7a99a;padding:6px 10px;max-width:560px;margin-bottom:18px}
    .ch4 .homebox4 span{margin-right:8px;color:#888}
    .ch4 .homebox4 input{flex:1;border:0;outline:0;font-size:14px;background:transparent}
    .ch4 .bgrp{background:#f0e0d6;border:1px solid #d9bfb7;margin:10px 0;padding:10px 14px}
    .ch4 .bgrp h3{margin:0 0 8px 0;font-size:13px;color:#800;text-transform:uppercase;letter-spacing:.5px;border-bottom:1px solid #d9bfb7;padding-bottom:4px}
    .ch4 .bgrp-items{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:6px 12px;font-size:13px}
    .ch4 .bgrp-items a.bd{color:inherit;text-decoration:none;display:flex;gap:6px;align-items:baseline;padding:2px 0}
    .ch4 .bgrp-items a.bd:hover{background:#fff}
    .ch4 .bgrp-items .bd-code{color:#af0a0f;font-weight:bold;font-family:Menlo,monospace;width:54px;flex-shrink:0}
    .ch4 .bgrp-items .bd-name{color:#222}
    .ch4 .stat4{color:#666;font-size:11px;margin-top:18px;border-top:1px solid #d9bfb7;padding-top:8px}
    .ch4 .examples4{font-size:12px;color:#444;margin-bottom:14px}
    .ch4 .examples4 a{color:#34345c}
  </style>
  <div class="ch4">
    <h1 class="brand4">virtual<span class="cn">-4chan</span></h1>
    <p class="tag">The boards are real names. Every thread, every reply, every linked page is hallucinated by a local language world model the moment you click. Pages persist in SQLite — once visited, a thread stays exactly as it was.</p>
    <div class="modelpill4">⚡ powered by <code>${esc(getSettings().model)}</code></div>
    <form id="homebox" class="homebox4" autocomplete="off">
      <span>🔍</span>
      <input id="homeinput" placeholder="archive search across boards, or type any 4chan URL" spellcheck="false" autofocus>
    </form>
    <div class="examples4">
      try:
      <a href="/search?q=${encodeURIComponent('what does /g/ think of nixos')}">what does /g/ think of nixos</a> ·
      <a href="/search?q=${encodeURIComponent('greentext story late night')}">greentext story late night</a> ·
      <a href="/view?url=${encodeURIComponent('https://boards.4chan.org/g/')}&ctx=${encodeURIComponent('/g/')}">boards.4chan.org/g/</a>
    </div>
    ${groups}
    <div class="stat4">This universe currently holds <b>${stats.pages}</b> pages across <b>${stats.serps}</b> searches.</div>
  </div>`;
  return shell({ title: 'virtual-4chan — local world model', address: '', content, boot: { mode: 'home', cached: true } });
}

export function renderSerp(opts: { query: string; cachedHtml?: string }): string {
  const inner = opts.cachedHtml ?? skeletonSerp();
  const content = `<div id="serp-root" class="serp-wrap">${inner}</div>${overlay()}`;
  return shell({
    title: `${opts.query} — LLMnet Search`,
    address: opts.query,
    content,
    boot: { mode: 'serp', cached: !!opts.cachedHtml, q: opts.query },
  });
}

export function renderPage(opts: { fakeUrl: string; from?: string; ctx?: string; cached: boolean }): string {
  const iframe = opts.cached
    ? `<iframe id="page-frame" sandbox="allow-same-origin allow-top-navigation-by-user-activation allow-popups allow-forms" src="/raw?url=${encodeURIComponent(opts.fakeUrl)}"></iframe>`
    : `<iframe id="page-frame" sandbox="allow-same-origin allow-top-navigation-by-user-activation allow-popups allow-forms"></iframe>`;
  const content = `${iframe}${overlay()}`;
  return shell({
    title: opts.fakeUrl,
    address: opts.fakeUrl,
    content,
    boot: { mode: 'page', cached: opts.cached, url: opts.fakeUrl, from: opts.from, ctx: opts.ctx },
  });
}

export function renderErrorBody(message: string, links: string[] = []): string {
  // A styled, in-universe error page that STILL contains working links so the
  // user can keep browsing instead of hitting a dead end.
  const linkHtml = links.map((l) => `<li><a href="/view?url=${encodeURIComponent(l)}" target="_top">${esc(l)}</a></li>`).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body{font-family:system-ui,sans-serif;background:#fff;color:#202124;display:flex;min-height:100vh;align-items:center;justify-content:center;margin:0}
    .box{max-width:560px;padding:40px;text-align:center}
    h1{font-size:42px;margin:0}.sub{color:#5f6368;margin:12px 0 24px}
    code{background:#f1f3f4;padding:2px 6px;border-radius:4px}
    ul{text-align:left;display:inline-block}
  </style></head><body><div class="box">
    <h1>This page failed to materialize</h1>
    <p class="sub">${esc(message)}</p>
    ${links.length ? `<p>But these places exist:</p><ul>${linkHtml}</ul>` : ''}
  </div></body></html>`;
}

export function renderSettings(
  cur: Settings,
  def: Settings,
  ping: { ok: boolean; detail: string },
): string {
  const presets = [
    { name: 'LM Studio (local)', baseUrl: 'http://127.0.0.1:1234/v1' },
    { name: 'Ollama (local)', baseUrl: 'http://127.0.0.1:11434/v1' },
    { name: 'OpenRouter', baseUrl: 'https://openrouter.ai/api/v1' },
    { name: 'OpenAI', baseUrl: 'https://api.openai.com/v1' },
  ];
  const presetBtns = presets
    .map((p) => `<button type="button" class="preset" data-url="${esc(p.baseUrl)}">${esc(p.name)}</button>`)
    .join('');
  const content = `<div class="settings">
    <h1>Settings</h1>
    <p class="sub">Point this app at any OpenAI-compatible chat endpoint. Defaults to local LM Studio.
      Best results come from the world model it was built for — <code>${esc(def.model)}</code>.</p>

    <div class="status-line ${ping.ok ? 'ok' : 'bad'}" id="conn">${ping.ok ? '● connected' : '● not reachable'} — ${esc(ping.detail)}</div>

    <form id="settings-form">
      <label>Endpoint base URL <span>OpenAI-compatible, ends in <code>/v1</code></span>
        <input name="baseUrl" id="f-baseUrl" value="${esc(cur.baseUrl)}" spellcheck="false" placeholder="http://127.0.0.1:1234/v1">
      </label>
      <div class="presets">${presetBtns}</div>

      <label>Model id
        <input name="model" id="f-model" value="${esc(cur.model)}" spellcheck="false" placeholder="${esc(def.model)}">
      </label>

      <label>API key <span>ignored by local servers; required by hosted providers — write-only, never echoed back</span>
        <input name="apiKey" id="f-apiKey" type="password" value="" spellcheck="false" placeholder="${cur.apiKey && cur.apiKey !== def.apiKey ? '••••••• (set — leave blank to keep)' : esc(def.apiKey)}" autocomplete="off">
      </label>

      <label class="check">
        <input type="checkbox" name="thinking" id="f-thinking" ${cur.thinking ? 'checked' : ''}>
        <span>Thinking mode <small>let the world model reason before generating each page — higher fidelity, much slower. Experimental on local hardware (see README).</small></span>
      </label>

      <div class="actions">
        <button type="submit" class="primary">Save</button>
        <button type="button" id="test">Test connection</button>
        <button type="button" id="reset" class="ghost">Reset to defaults</button>
        <span id="saved" class="saved" hidden>Saved ✓</span>
      </div>
    </form>
  </div>
  <script>
    (function(){
      var f=document.getElementById('settings-form');
      var conn=document.getElementById('conn');
      document.querySelectorAll('.preset').forEach(function(b){ b.addEventListener('click',function(){ document.getElementById('f-baseUrl').value=b.dataset.url; }); });
      function payload(){ return { baseUrl:f.baseUrl.value, model:f.model.value, apiKey:f.apiKey.value, thinking:f.thinking.checked }; }
      function setConn(p){ conn.className='status-line '+(p.ok?'ok':'bad'); conn.textContent=(p.ok?'● connected':'● not reachable')+' — '+p.detail; }
      f.addEventListener('submit', async function(e){ e.preventDefault();
        var r=await fetch('/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});
        var j=await r.json(); if(j.ping) setConn(j.ping);
        var s=document.getElementById('saved'); s.hidden=false; setTimeout(function(){s.hidden=true;},2000);
      });
      document.getElementById('test').addEventListener('click', async function(){
        conn.textContent='● testing…'; conn.className='status-line';
        await fetch('/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});
        var r=await fetch('/health'); var j=await r.json(); setConn(j.model);
      });
      document.getElementById('reset').addEventListener('click', function(){
        f.baseUrl.value=${JSON.stringify(def.baseUrl)}; f.model.value=${JSON.stringify(def.model)}; f.apiKey.value=${JSON.stringify(def.apiKey)}; f.thinking.checked=${def.thinking};
      });
    })();
  </script>`;
  return shell({ title: 'Settings — virtual-4chan', address: '', content, boot: { mode: 'settings', cached: true } });
}

function overlay(): string {
  return `<div id="overlay" hidden>
    <div class="loadcard">
      <div class="spinner"></div>
      <div class="status" id="status">Connecting…</div>
      <div class="bar"><div class="bar-fill" id="bar"></div></div>
      <pre class="source" id="source"></pre>
      <div class="hint">The origin server is generating this page token by token.</div>
    </div>
  </div>`;
}

function skeletonSerp(): string {
  const row = `<div class="sk-result"><div class="sk-line sk-crumb"></div><div class="sk-line sk-title"></div><div class="sk-line"></div><div class="sk-line short"></div></div>`;
  return `<div class="sk-serp">${row.repeat(6)}</div>`;
}
